# Generated by Django 4.1.4 on 2023-08-02 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appname", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("price", models.IntegerField(default=50)),
                ("description", models.TextField(default="Its too yummy")),
                ("image", models.ImageField(upload_to="images")),
                ("order_status", models.BooleanField(default=False)),
                ("items", models.IntegerField(default=0)),
            ],
        ),
    ]
